/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        surface: "var(--stitch-surface)",
        "surface-dim": "var(--stitch-surface-dim)",
        "surface-bright": "var(--stitch-surface-bright)",
        "surface-container-lowest": "var(--stitch-surface-container-lowest)",
        "surface-container-low": "var(--stitch-surface-container-low)",
        "surface-container": "var(--stitch-surface-container)",
        "surface-container-high": "var(--stitch-surface-container-high)",
        "surface-container-highest": "var(--stitch-surface-container-highest)",
        "on-surface": "var(--stitch-on-surface)",
        "on-surface-variant": "var(--stitch-on-surface-variant)",
        outline: "var(--stitch-outline)",
        "outline-variant": "var(--stitch-outline-variant)",
        "on-primary": "var(--stitch-on-primary)",
        "primary-container": "var(--stitch-primary-container)",
        "on-primary-container": "var(--stitch-on-primary-container)",
        secondary: "var(--stitch-secondary)",
        "on-secondary": "var(--stitch-on-secondary)",
        error: "var(--stitch-error)",
        "on-error": "var(--stitch-on-error)",
        "error-container": "var(--stitch-error-container)",
        "on-error-container": "var(--stitch-on-error-container)",
      },
      fontFamily: {
        sans: ["Inter", "Manrope", "Hanken Grotesk", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", fontWeight: "700", letterSpacing: "0" }],
        "headline-lg": ["30px", { lineHeight: "38px", fontWeight: "700", letterSpacing: "0" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600", letterSpacing: "0" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600", letterSpacing: "0" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-bold": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "container-margin": "40px",
        gutter: "16px",
      },
      borderRadius: {
        lg: "0.5rem",
        md: "0.375rem",
        sm: "0.25rem",
      },
    },
  },
  plugins: [],
};

