export const ROUTES = {
  home: "/",
  explore: "/explore",
  login: "/login",
  register: "/register",
  verifyEmail: "/verify-email",
  studentDashboard: "/student/dashboard",
  studentProfile: "/student/profile",
  studentSavedOpportunities: "/student/saved",
  studentApplications: "/student/applications",
  opportunityDetail: "/opportunities",
  organizationDashboard: "/organization/dashboard",
  organizationProfile: "/organization/profile",
  organizationOpportunities: "/organization/opportunities",
  organizationApplicants: "/organization/applicants",
  adminDashboard: "/admin/dashboard",
  adminPendingOpportunities: "/admin/opportunities/pending",
  adminReports: "/admin/reports",
  adminUsers: "/admin/users",
  adminOrganizationVerifications: "/admin/organization-verifications",
  adminCategories: "/admin/categories",
};
